config/routes.rb
Rails.application.routes.draw do

  root "articles#index"

  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  default_scope {order(created_at: :desc)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

def new

  @article = Article.new
end

def create
  @article = Article.new(article_params)
  if @article.save
    flash[:success] = "Post has been created"
    redirect_to articles_path
  else
    flash.now[:danger] = "Post has not been created"
    render :new
end
end

private
def article_params
  params.require(:article).permit(:title, :body)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/index.html.erb
<%= link_to "New Article", new_article_path, class: "btn btn-default btn-lg", id: "new-article-btn" %>

<% if @articles.empty? %>
<h1 id="no-posts">No Posts Created </h1>
<% else %>


  <% @articles.each do |article|%>
  <div class="well well-lg">
    <div class="article-title">

      <%= link_to article.title, article_path(article) %>
    </div>
    <div class="article-body">
      <%= truncate(article.body, length: 500) %>
    </div>
  </div>

  <% end %>
  <% end %>

app/views/articles/new.html.erb
<h3 class='text-center'>Adding New Post</h3>
<div class='row'>
  <div class='col-md-12'>
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <% if @article.errors.any? %>

    <div class="panel panel-danger col-md-offset-1">
      <div class="panel-heading">
  <h2 class="panel-title">
    <%= pluralize(@article.errors.count, "errors")%>
  prohibited post from being saved:</h2>
<div class="panel-body">
  <% @article.errors.full_messages.each do |msg| %>
  <li>
    <%= msg %>
  </li>

  <% end %>
</div>

  </div>

</div>





    <% end %>
    <div class='form-group'>
        <div class='control-label col-md-1'>
        <%= f.label :title %>
        </div>
    <div class='col-md-11'>
      <%= f.text_field :title, class: 'form-control', placeholder: 'Title of article', autofocus: true %>
    </div>
    </div>
  <div class='form-group'>
    <div class='control-label col-md-1'>
    <%= f.label :body %>
    </div>
    <div class='col-md-11'>
    <%= f.text_area :body, rows: 10, class: 'form-control', placeholder: 'Body of article' %>
    </div>
  </div>
      <div class='form-group'>
        <div class='col-md-offset-1 col-md-11'>
          <%= f.submit "Create Post", class: 'btn btn-primary btn-lg btn-block pull-right'  %>
        </div>
      </div>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaizApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header role="banner">

      <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">FaizApp</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">


      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  </header>
<div class="container">
  <div class="row">


<div class="col-md-12">
        <% flash.each do |key, message| %>
        <div class="text-center alert alert <%= key == 'notice'? 'success':'danger' %>">
          <%= message %>
        </div>

        <% end %>
    <%= yield %>
    </div>
      </div>
    </div>
  </body>
</html>